[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3

[k8s_nodes]
node1.nutriflow.internal ansible_host=10.0.10.21
node2.nutriflow.internal ansible_host=10.0.11.22

[bastion]
bastion.nutriflow.internal ansible_host=10.0.1.50
