apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: nutriflow
spec:
  type: ClusterIP
  selector:
    app: nutriflow-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
